### ISSUE TITLE
Non blocking RX

### ISSUE THREAD

**Issue by WilixLead** [nerdralph/picoUART#1]
Has any way to detect transmission start? I can't block program flow with pu_rx(), but really need to wait new command.

**Comment by nerdralph** [comment]
Interrupt-based Rx is something I've been planning for a while.  Just in the last few days I finished doing some interrupt latency measurements, so I can adjust the Rx timing for the interrupt latency.
I could also implement a blocking Rx with timeout if that would be useful.

**Comment by WilixLead** [comment]
Thank you for answer. I already implement IRQ / INT0 based detection of first incoming byte (just waiting line changing). So I loose first byte (interrupt latency), but I can fill RX buffer. In the master side I can implement line state changing before start transmitting. If you implement non blocking reading or transmission detection (for first byte, but all transmission can be 1 byte :)) - it will be really great.

**Comment by nerdralph** [comment]
As you wish.
https://github.com/nerdralph/picoUART/releases/tag/v1.0.0

**Comment by WilixLead** [comment]
It is very cool! Thank you! 
But I think you should add some more instructions in readme :) So, I can't use INT0? Or I can't use any other PCINT port?

**Comment by nerdralph** [comment]
I don't mention INT0 in the Readme because INT0 is not used in any way by picoUART.  I'll think about how I can describe the way pin change interrupts are used without making it confusing for users of the library that are not intending to modify the source code.
If you look at the source you'll see it uses the PCINT0 interrupt, and assumes it is associated with PORTB (like on the t13 and t85).  The t84, which uses PORTA for pin-change interrupts, is not currently supported.

**Comment by WilixLead** [comment]
Yes. I see PORTB and other. I just not sure, can I change PCINT0 to PCINT1 (for example) ?

**Comment by nerdralph** [comment]
The port/pin register and the PCINT vector have to match.  Which AVR are you using?

**Comment by WilixLead** [comment]
I use ATTiny13 and it match. But I already have few devices with TX/RX on PB1 for example. So my questions is "Can I just change PCINT0 to PCINT1 in current sources?" 
I just don't know about latency on non PCINT0 interrupts :) I hope they are should be same but not sure

**Comment by nerdralph** [comment]
The t13 doesn't have a PCINT1 vector, only PCINT0.  The default in pu_config is to use PB0 for transmit and PB1 for receive.  To change it to another pin, change line 9.
https://github.com/nerdralph/picoUART/blob/master/src/pu_config.h#L8

**Comment by WilixLead** [comment]
Ah. Sorry. All time we talk about interrupt vector and mask name :) Thank you for help, I try this as soon as return to project :)
