### ISSUE TITLE
Compilation error.

### ISSUE THREAD

**Issue by Dimitry-Muzi** [nerdralph/picoUART#3]
Hello. When trying to compile any of the examples, it produces a compilation error.

Arduino: 1.8.12 (Windows 10), Board:"ATtiny13, 9.6 MHz internal osc., BOD 4.3V, Micros enabled"

In file included from C:\Temp\arduino_modified_sketch_421875\echo.ino:2:0:

C:\Users\Dimitry\Documents\Arduino\libraries\picoUART-1.1.1\src/pu_print.h:4:17: error: conflicting declaration of 'void prints(const char*)' with 'C' linkage

 extern "C" void prints(const char* s);

                 ^~~~~~

In file included from C:\Users\Dimitry\AppData\Local\Arduino15\packages\MicroCore\hardware\avr\1.0.6\cores\microcore/HalfDuplexSerial.h:28:0,

                 from C:\Users\Dimitry\AppData\Local\Arduino15\packages\MicroCore\hardware\avr\1.0.6\cores\microcore/Arduino.h:123,

                 from sketch\echo.ino.cpp:1:

C:\Users\Dimitry\AppData\Local\Arduino15\packages\MicroCore\hardware\avr\1.0.6\cores\microcore/picoUART.h:71:6: note: previous declaration with 'C++' linkage

 void prints(const char* s);

      ^~~~~~

exit status 1
Compilation error for the board ATtiny13.

**Comment by nerdralph** [comment]
MicroCore already uses picoUART, which is why you get the duplicate
definitions.

**Comment by Dimitry-Muzi** [comment]
Thank you.
