### ISSUE TITLE
Example of using serial commands

### ISSUE THREAD

**Issue by Kaspi314** [nerdralph/picoUART#5]
Can you make an example of using serial commands that toggle an LED for example by sending 1 or 0 or do other tasks between pauses is use of the uart. Toggling the uart on/off or even switching pins on the fly?

the reason being I cannot even get the ISR echo to allow me to toggle an LED on a digispark attiny85 board. (pin 1) while using pin 0 rx and pin 4 tx. It just spams the console with the first character of the last line sent.

I'm not sure why this works this way but I would imagine I should be able to delay? or do I need to implement a timer?

I really would love to use this with a 16 channel multiplexer demultiplexer (CD74HC4067).. one wire. half duplex and being able to control things on 1 wire half duplex and listen/wait intermittently, rx/tx but it doesn't seen to be working even toggling a single LED for me on a different pin without it spamming the console "got: ??????????????"

e.g. measure analog or output on the pin. toggle other pins to address..

Ideally I only want to enable the serial for a specific duration of time. Maybe 100ms or 5 minutes waiting for rx. or just during tx and timeout for a reply.

Here is my try at it:

```
#include <pu_print.h>
#include <picoUART.h>
const int buflen = 20;
char linebuf[buflen];
bool ledstate = false;

int readline()
{
  int count = 0;
  char c;
  do {
    while ( ! purx_dataready() );   // wait for data
    c = pu_read();
    linebuf[count++] = c;
  } while ( (c != '\n') && (count < buflen - 1) );
  linebuf[count] = '\0';
  return count;
}

void setup()
{
  pinMode(1, OUTPUT);
  ledstate = 0;
  prints("\nrxISR line echo\n");
}

void loop()
{

  if ( purx_dataready() )
  {
    readline();
    prints(ledstate ? "\n1:" : "\n0:");
    prints("got: ");
    prints(linebuf);
  }

  switch (linebuf[0]) 
{
    case '0' : {
        digitalWrite(1, LOW);
        ledstate = 0;
      }
    case '1' : {
        digitalWrite(1, HIGH);
        ledstate = 1;
      }
  }
}
```

settings:
```// port and bit for Tx and Rx - can be same
#define PU_TX B,4
#define PU_RX B,0

// disable interrupts during Tx and Rx
#define PU_DISABLE_IRQ 1

**Comment by nerdralph** [comment]
Although I recommend against embedded developers using any Arduino core, I have tested picoUART with picoCore.
https://github.com/nerdralph/picoCore
MicroCore is another option, as Hans has integrated picoUART for serial communications.
https://github.com/MCUdude/MicroCore
I've helped Spence in the past, so I'd consider supporting ATtinyCore as well if there is a simple way to disable the built-in Serial implementation.
https://github.com/SpenceKonde/ATTinyCore
The Digistump Arduino core has been abandoned, and I have no intention of supporting it.

**Comment by Kaspi314** [comment]
I'll try these I don't really understand these cores but I am guessing there is a way to just add them to an arduino project in the arduino ide. It seems that I am using attiny core and have the 8mhx bootloader burned. 

https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json

but will try with picocore and microcore on attiny85 if it will work. I am guessing this is expected to be more promising at blinking an LED or toggling pins?

I don't really understand what is going on in the code here or I would try harder. I see the ISR being set on but not where it is turned off in methods and am trying to simply disable and reassign pins and re-enable UART.

**Comment by nerdralph** [comment]
If you don't understand how the Arduino cores work, then you should probably start with using avr-gcc and avr-libc to compile a simple program with a main() function.

**Comment by Kaspi314** [comment]
> If you don't understand how the Arduino cores work, then you should probably start with using avr-gcc and avr-libc to compile a simple program with a main() function.

Thanks!

I have figured it out. I definitely think i understand setup() and loop() in the arduino (and mostly have experience with python, java, php. but this is not too hard)

I have figured out how to add "hardware"

Troubleshooting brings up the issue with the serial RX on these boards I have: only pin 1 works for RX and all other pins will trigger constant spamming of the serial.

This is further tested with the picoCore as well.

I have tried also duplicating the 1k resistor and diode pulldown  on other pins (similar to the built in diode) but have not achieved a successful serial console.

(unplugging the usb-ttl TX - RX on the attiny, yields a quiet output.)

I would really love to find that this can work in half duplex on the ADC pins.

I'm using this exact model from Amazon: https://www.amazon.com/gp/product/B08G86Z6FD

It claims to have built in serial and usb but that is obviously not the case.

I may try with the pico boot loader. I'm not sure if there is some reason and the fuses need to be set differently or what.

**Comment by Kaspi314** [comment]
I managed to get the single wuire half duplex kind of working. I used an 2N2222 transistor (it just says npn type in the schematic)

But I am not sure why does the serial port come back with a bunch of ? symbols and very dirty.

This is using picocore and it is worse with picocore than arduino core (slightly)

both manage to echo back the character but where it says "got: " it comes back gibberish on pin 4 (a2):

Code:

```
#include <picoUART.h>
#include <pu_print.h>
#include <stdlib.h>
const int mdepth = 4;
uint8_t menustp[mdepth];
int int_i;
char itoa_i[7];

void setup() {}

void loop()
{
LOOPB:
int_i=0;
while(int_i<mdepth - 1) {
  menustp[int_i] = false;
  ++int_i;
}
LOOPA:
  uint8_t c;
  if (!menustp[0])
  {
    prints("\r\npicoUART echo");
  }
  c = purx();
  prints("got: ");
  putx(c);
  prints("\r\n");
  if (!menustp[0])
  {

    switch (c)
    {
      case 'a':
        {
          menustp[0] = 'a';
          prints("a>");
          delay(1000);
          int_i = analogRead(A2);
          delay(1000);
          itoa(int_i,itoa_i,10);
          for(int_i = 0; int_i < 7; int_i++) {
            putx(itoa_i[int_i]);
          }
        }
    }
  }
}
```

and I see this in serial:

```
SEND: z\n
⸮⸮⸮ z
SEND: x\n
picoUART echo⸮⸮⸮ x
SEND: c\n
picoUART echo⸮⸮⸮ c
SEND:v\n
picoUART echo⸮⸮⸮ v
SEND: b\n
picoUART echo⸮⸮⸮ b
SEND: a\n
picoUART echo⸮⸮⸮ a
a>584
```

is there a better way to sync the serial if that is the problem?

it works better when I put the wire to the input pin to the collector with the RX from the TTL dongle. CH340.

**Comment by Kaspi314** [comment]
Nevermind I'm an idiot. It needs a delay after purx();

delay(50); fixed it.

(9600) baud
