### ISSUE TITLE
pin change interrupts

### ISSUE THREAD

**Issue by theduskin** [nerdralph/picoUART#7]
I don't mention INT0 in the Readme because INT0 is not used in any way by picoUART.  **I'll think about how I can describe the way pin change interrupts are used without making it confusing for users of the library that are not intending to modify the source code.**

_Originally posted by @nerdralph in https://github.com/nerdralph/picoUART/issues/1#issuecomment-629658872_

this is exactly what I'm looking/waiting for.
not that urgent at the moment, just to let you know there's at least one interested.

**Comment by nerdralph** [comment]
I decided that code comments are the best place to document internal
implementation details. For example:
https://github.com/nerdralph/picoUART/blob/master/src/rxISR.cpp#L14

**Comment by theduskin** [comment]
yes, thank you. i've read that, (not understanding ;) )
i've done the following, what makes it build without errors.
communication works a little, means something happen sometimes.
renaming the ISR (and added to picoUART.h to make it visible):
`ISR(PCINT0_vect, `ISR_NAKED)`

to

`void ISRR(void)`

and attach it to the PinChangeInterrupt lib this way:
` attachPCINT(4, ISRR, CHANGE);`

iv'e also changed PinChangeInterrupt's `ISR(PCINT0_vect)`to `ISR(PCINT0_vect, ISR_NAKED)`and added a `reti(); `at the end.

the word cycles occurs in your comments more than once.
makes me hope that there are some tuning is possible?
or is that a complete wrong way?

**Comment by nerdralph** [comment]
picoUART must have control over the pin change interrupt.  Using a pin change library is a bad idea.
