### ISSUE TITLE
TX and RX ports are hardcoded

### ISSUE THREAD

**Issue by adrcunha** [nerdralph/picoUART#8]
Unlike the port baud rate, the TX and RX pins are hardcoded in `pu_config.h`:

```
#ifndef PU_BAUD_RATE
#define PU_BAUD_RATE 115200L            // default baud rate
#endif

// port and bit for Tx and Rx - can be same
#define PU_TX B,0
#define PU_RX B,1
```

**Comment by nerdralph** [comment]
I wanted to come up with a way that would work both with Arduino and when building with make.  I never did find an easy way to add defines to Arduino builds, so I may just settle on doing it with the conditional defines in pu_config.h.
